# Generated by Django 4.2.16 on 2024-10-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Adjuster", "Adjuster"),
                            ("Employer_or_Lawyer", "Employer_or_Lawyer"),
                        ],
                        default="Adjuster",
                        max_length=20,
                        verbose_name="Position",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "employer_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Employer Name",
                    ),
                ),
                (
                    "date_of_injury",
                    models.DateField(verbose_name="Date of Injury/Accident"),
                ),
                (
                    "time_of_injury",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Time of Injury/Accident"
                    ),
                ),
                (
                    "location_of_injury",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Location of Injury/Accident",
                    ),
                ),
                (
                    "circumstances_of_injury",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Circumstances of Injury/Accident",
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(max_length=200, verbose_name="Insurance Company"),
                ),
                (
                    "policy_number",
                    models.CharField(max_length=100, verbose_name="Policy Number"),
                ),
                (
                    "claim_number",
                    models.CharField(max_length=100, verbose_name="Claim Number"),
                ),
                (
                    "adjuster_full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Adjuster's Full Name",
                    ),
                ),
                (
                    "adjuster_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Adjuster's Phone Number",
                    ),
                ),
                (
                    "adjuster_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Adjuster's Email Address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_file", models.FileField(upload_to="medical_records/")),
                (
                    "referral_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="app.referralform",
                    ),
                ),
            ],
        ),
    ]
